### ISSUE TITLE
M4 experiment is not avalable

### ISSUE THREAD

**Issue by Dolores2333** [ElementAI/N-BEATS#12]
The M4 dataset url link in the script is not available. Though I mannually downloaded the datasets from [M4Competition](https://github.com/Mcompetitions/M4-methods) , the make run command still fails.

**Comment by Dolores2333** [comment]
Wired. If I move download method in dataset/m4.py out of the class and run it first then the download process is ok. But errors reported if I use download method as a class method which is exactly use by the author.

**Comment by hamdi** [comment]
Encountered this issue too because the download links for the M4 dataset are dead. Solved it by replacing them with the following links:
TRAINING_DATASET_URL = 'https://git.islab.ntua.gr/stralex/m3-m4/raw/master/data/M4DataSet.zip'
TEST_DATASET_URL = 'https://git.islab.ntua.gr/stralex/m3-m4/raw/master/data/M-test-set.zip'
INFO_URL = 'https://git.islab.ntua.gr/stralex/m3-m4/raw/master/data/M4Info.csv'
